"""Small command-line chat demo for the trained Task 2 mini-GPT model."""

from __future__ import annotations

import argparse
from pathlib import Path

import torch
from torch import Tensor

from src.model import MiniGPT, load_for_eval
from src.tokenizer import BPETokenizer


def parse_args() -> argparse.Namespace:
    """Parse interactive and one-shot generation options."""
    parser = argparse.ArgumentParser(
        description="Load the trained mini-GPT checkpoint and generate responses."
    )
    parser.add_argument("--checkpoint", type=Path, default=Path("ckpt/best.pt"))
    parser.add_argument("--prompt", help="Run one turn and exit instead of chatting.")
    parser.add_argument("--max-new-tokens", type=int, default=24)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-k", type=int, default=40)
    parser.add_argument("--top-p", type=float, default=0.9)
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "mps", "cuda"),
        default="auto",
    )
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def resolve_device(requested: str) -> torch.device:
    """Select the requested device or the best available accelerator."""
    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")

    if requested == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA is not available in this PyTorch environment")
    if requested == "mps" and not torch.backends.mps.is_available():
        raise RuntimeError("MPS is not available in this PyTorch environment")
    return torch.device(requested)


def validate_args(args: argparse.Namespace) -> None:
    """Reject sampling settings that the model cannot handle safely."""
    if args.max_new_tokens <= 0:
        raise ValueError("--max-new-tokens must be positive")
    if args.temperature < 0:
        raise ValueError("--temperature cannot be negative")
    if args.top_k <= 0:
        raise ValueError("--top-k must be positive")
    if not 0 < args.top_p <= 1:
        raise ValueError("--top-p must be in (0, 1]")


def safe_decode(tokenizer: BPETokenizer, token_ids: list[int]) -> str:
    """Decode generated byte tokens, replacing a final invalid UTF-8 sequence."""
    raw_bytes = b"".join(tokenizer.vocab_id_to_token[token_id] for token_id in token_ids)
    return raw_bytes.decode("utf-8", errors="replace")


def encode_context(
    tokenizer: BPETokenizer,
    history_ids: list[int],
    user_text: str,
    context_limit: int,
    device: torch.device,
) -> Tensor:
    """Append one user turn and retain the newest IDs that fit the context."""
    turn_ids = tokenizer.encode(f"用户：{user_text}\n助手：")
    context_ids = (history_ids + turn_ids)[-context_limit:]
    if not context_ids:
        raise ValueError("The encoded prompt is empty")
    return torch.tensor([context_ids], dtype=torch.long, device=device)


def generate_response(
    model: MiniGPT,
    tokenizer: BPETokenizer,
    history_ids: list[int],
    user_text: str,
    max_new_tokens: int,
    temperature: float,
    top_k: int,
    top_p: float,
    device: torch.device,
) -> tuple[str, list[int]]:
    """Generate one assistant continuation while respecting ``block_size``."""
    generation_length = min(max_new_tokens, model.block_size - 1)
    context_limit = model.block_size - generation_length
    prompt_ids = encode_context(
        tokenizer, history_ids, user_text, context_limit, device
    )

    output_ids = model.generate(
        prompt_ids,
        max_new_tokens=generation_length,
        top_k=top_k,
        top_p=top_p,
        temperature=temperature,
    )
    generated_ids = output_ids[0, prompt_ids.shape[1] :].detach().cpu().tolist()
    response = safe_decode(tokenizer, generated_ids)

    # Preserve exact generated IDs for the next turn; decoding is display-only.
    next_history_ids = output_ids[0].detach().cpu().tolist()
    next_history_ids.extend(tokenizer.encode("\n"))
    return response.strip(), next_history_ids[-model.block_size :]


def load_model(
    checkpoint: Path,
    device: torch.device,
) -> tuple[MiniGPT, BPETokenizer]:
    """Load a matching checkpoint/tokenizer pair and move the model to a device."""
    if not checkpoint.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint}")

    model, tokenizer = load_for_eval(checkpoint)
    model = model.to(device)
    model.eval()
    return model, tokenizer


def interactive_chat(
    model: MiniGPT,
    tokenizer: BPETokenizer,
    args: argparse.Namespace,
    device: torch.device,
) -> None:
    """Run a terminal chat loop with reset and exit commands."""
    history_ids: list[int] = []
    print("输入 /clear 清空历史，输入 /quit 退出。")
    print("提示：该模型只在唐诗小语料上预训练，回答更接近文本续写。")

    while True:
        try:
            user_text = input("\n你：").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n对话结束。")
            return

        if not user_text:
            continue
        if user_text == "/quit":
            print("对话结束。")
            return
        if user_text == "/clear":
            history_ids.clear()
            print("历史已清空。")
            continue

        response, history_ids = generate_response(
            model,
            tokenizer,
            history_ids,
            user_text,
            args.max_new_tokens,
            args.temperature,
            args.top_k,
            args.top_p,
            device,
        )
        print(f"GPT：{response}")


def main() -> None:
    """Load artifacts and run either one-shot or interactive generation."""
    args = parse_args()
    validate_args(args)
    torch.manual_seed(args.seed)

    device = resolve_device(args.device)
    model, tokenizer = load_model(args.checkpoint, device)
    print(
        f"Loaded {args.checkpoint} on {device}; "
        f"vocab={tokenizer.vocab_size}, block_size={model.block_size}."
    )

    if args.prompt is not None:
        response, _ = generate_response(
            model,
            tokenizer,
            [],
            args.prompt,
            args.max_new_tokens,
            args.temperature,
            args.top_k,
            args.top_p,
            device,
        )
        print(f"你：{args.prompt}\nGPT：{response}")
        return

    interactive_chat(model, tokenizer, args, device)


if __name__ == "__main__":
    main()
